services:
  postgis:
    image: postgis/postgis
    container_name: flood_postgis
    restart: always
    environment:
      - POSTGRES_DB=cmu_flood
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./postgis/:/docker-entrypoint-initdb.d
    ports:
      - 5437:5432

  nodejs:
    image: node
    container_name: flood_nodejs
    working_dir: /app/nodejs
    restart: always
    depends_on:
      - postgis
    environment:
      - NODE_ENV=production
    volumes:
      - ./nodejs:/app/nodejs
    ports:
      - 3600:3600
    command: bash -c "npm i && npm i -g nodemon && nodemon server.js"
