

###
# GET https://sheets.googleapis.com/v4/spreadsheets/1H8XAEH8ceZGdmBT1jWAv2TA1P40IInD3BqO3OVaqvgE/values/Form Responses 1?alt=json&key=AIzaSyDBvLZMFRD_cQB-O9tvof3EpF7_KQwMK0w
//https://docs.google.com/forms/d/e/1FAIpQLSeIG5QqRYGdQ_MMYtfRjglSaj19uJw18MU3_X_ptoi0OmCzbg/viewform?usp=pp_url&entry.28548348=sakda

POST http://localhost:3600/api/insertdata HTTP/1:1
Content-Type: application/json

{
      "data":{
            "wlevel":"01",
            "des":"01" , 
            "help":"00002",
            "img": "ddd"
      }        
}



###
GET http://localhost:3600/api/getdata1
Content-Type: application/json